### ISSUE TITLE
Fallback link is hard to read if the site uses a background color on links

### ISSUE THREAD

**Issue by cbirdsong** [mrwweb/enhanced-embed-block#8]
Our theme has a little color tint when you hover over a link:

![A link with a dark green underline and a light green background color. Imagine a mouse pointer is hovering over it.](https://github.com/mrwweb/enhanced-embed-block/assets/1672206/690196c7-f768-4e83-8938-43e229886d91)

That also applies to the `.lite-youtube-fallback` link if the `lite-youtube` script fails to load:

https://github.com/mrwweb/enhanced-embed-block/assets/1672206/8ca1a07c-62a5-46b8-85f3-3dc7ee244736

Easy solution:
- also apply the background color with `!important`

Complicated solution:
- stop changing the link color, and instead generate the background color from it by using some of those fancy new CSS color functions: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors

**Comment by mrwweb** [comment]
`!important` feels quite appropriate for this case. I'll get that on the roadmap.
